- name: Deploy via FTP
  uses: SamKirkland/FTP-Deploy-Action@4.0.0
  with:
    server: vh276.timeweb.ru
    username: ${{ secrets.TIMEWEB_USER }}
    password: ${{ secrets.TIMEWEB_PASS }}
    local-dir: ./dist
    server-dir: /domains/starunflow.ru/public_html
